openapi: '3.1.0'

info:
  title: HorologyService
  version: 1.0.0

servers:
  - url: /api
  - url: https://horology.cloud/api
    description: Do things with dates and times.

paths:
  /status:
    get:
      operationId: status
      responses:
        '200':
          description: Status endpoint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
  /adjust:
    get:
      operationId: adjust
      requestBody:
        description: The date information to adjust.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdjustmentRequest'
        required: true
      responses:
        '200':
          description: A success response with the resulting date.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdjustmentResponse'
        '400':
          description: An error response if the request could not be processed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /compare:
    get:
      operationId: compare
      requestBody:
        description: The dates to compare.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComparisonRequest'
        required: true
      responses:
        '200':
          description: A success response with the resulting difference.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComparisonResponse'
        '400':
          description: An error response if the request could not be processed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /convert/{to}:
    get:
      operationId: convert
      parameters:
        - in: path
          name: to
          schema:
            type: string
          required: true
          description: The unit value to convert to.
      requestBody:
        description: The date component to convert.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversionRequest'
        required: true
      responses:
        '200':
          description: A success response with the resulting conversion values.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversionResponse'
        '400':
          description: An error response if the request could not be processed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /calendars:
    get:
      operationId: getCalendars
      responses:
        '200':
          description: Returns a list of supported calendar identifiers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarIdList'

components:
  schemas:
    ErrorResponse:
      type: object
      description: Standard response body for errors.
      properties:
        code:
          type: string
        reason:
          type: string

    CalendarIdList:
      type: array
      items:
        type: string

    StatusResponse:
      type: object
      description: Status response.
      properties:
        date:
          type: string
        hostname:
          type: string

    DateFields:
      type: object
      description: A collection of DateTimeField values representing each of the components of a date.
      properties:
        year:
          $ref: '#/components/schemas/DateTimeField'
        month:
          $ref: '#/components/schemas/DateTimeField'
        day:
          $ref: '#/components/schemas/DateTimeField'
        hour:
          $ref: '#/components/schemas/DateTimeField'
        minute:
          $ref: '#/components/schemas/DateTimeField'
        second:
          $ref: '#/components/schemas/DateTimeField'

    DateTimeField:
      type: object
      description: A specific field for date/time values.
      properties:
        type:
          type: string
        value:
          type: integer
      required:
        - type
        - value

    DateComponents:
      type: object
      description: Individual values that make up a date
      properties:
        year:
          type: integer
        month:
          type: integer
        day:
          type: integer
        hour:
          type: integer
        minute:
          type: integer
        second:
          type: integer

    AdjustmentRequest:
      type: object
      description: An object specificying the date and adjustments to use.
      properties:
        date:
          $ref: '#/components/schemas/DateFields'
          description: The starting date on which to perform the adjustment.
        adjustments:
          $ref: '#/components/schemas/DateFields'
          description: The adjustments to make to the date to determine the resulting date.
        calendar:
          type: string
          description: The name of the calendar
        mode:
          type: string
          description: |
            The mode for performing the adjustment. This will determine whether
            the date, time, or both sets of components will be used.
          enum:
            - dateOnly
            - timeOnly
            - dateAndTime
      required:
        - date
        - adjustments
        - mode

    AdjustmentResponse:
      type: object
      description: Response object from an adjustment request.
      properties:
        date:
          type: string
        components:
          $ref: '#/components/schemas/DateComponents'
      required:
        - date
        - components

    ComparisonRequest:
      type: object
      description: An object specifying the two dates to compare.
      properties:
        fromDate:
          $ref: '#/components/schemas/DateFields'
        toDate:
          $ref: '#/components/schemas/DateFields'
        calendar:
          type: string
          description: |
            The identifier of the calendar to use. If not specified, the Gregorian calendar is
            used. See the '/calendars' endpoint for acquiring a list of valid, supported
            calendar identifiers.
        mode:
          type: string
          enum:
            - dateOnly
            - timeOnly
            - dateAndTime
      required:
        - fromDate
        - toDate
        - mode

    ComparisonResponse:
      type: object
      description: Response object from a comparison request.
      properties:
        difference:
          $ref: '#/components/schemas/DateFields'
      required:
        - difference

    ConversionRequest:
      type: object
      description: An object specifying the date component value to convert.
      properties:
        value:
          type: integer
        unit:
          type: string
      required:
        - value
        - unit

    ConversionResponse:
      type: object
      description: Response object from a conversion request.
      properties:
        value:
          type: integer
        approximate:
          type: boolean
        message:
          type: string
      required:
        - value
        - approximate
